# Generated by Django 3.2.7 on 2021-10-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='user',
            new_name='buyer_bidder',
        ),
    ]
