# Generated by Django 3.2.7 on 2021-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211010_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='productName',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default='cat', max_length=64),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='description',
            field=models.CharField(default='desc', max_length=64),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image_url',
            field=models.CharField(default='img url', max_length=64),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='title',
            field=models.CharField(default='title', max_length=64),
        ),
    ]
