# Generated by Django 3.2.7 on 2021-10-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.AuctionListing'),
        ),
    ]
