# Generated by Django 3.2.7 on 2021-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_auto_20211114_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='item',
            new_name='item_id',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.Comment'),
        ),
    ]
