# Generated by Django 3.2.7 on 2021-11-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_auto_20211119_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='bid',
            field=models.ManyToManyField(blank=True, null=True, related_name='bid', to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.Comment'),
        ),
    ]
