# Generated by Django 3.2.7 on 2021-11-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_auto_20211121_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.Comment'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing_id',
            field=models.ManyToManyField(blank=True, related_name='listing_id', to='auctions.AuctionListing'),
        ),
    ]
